from ui.complement.clickableWidget import QWidgetClickable

# Form implementation generated from reading ui file 'ui/floating_w.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
from ui.complement.QNews import QNews


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(340, 85)
        Dialog.setMinimumSize(QtCore.QSize(295, 85))
        Dialog.setMaximumSize(QtCore.QSize(500, 250))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icono.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        Dialog.setWindowIcon(icon)
        Dialog.setWindowOpacity(0.9)
        Dialog.setStyleSheet("QLabel {\n"
"    font: 12pt \"Segoe UI\";\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QDialog{\n"
"    background-color: rgb(29, 29, 29);\n"
"    border-radius: 10px;\n"
"}\n"
"")
        Dialog.setModal(False)
        self.gridLayout_2 = QtWidgets.QGridLayout(Dialog)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 9)
        self.gridLayout_2.setSpacing(5)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.title_bar = QtWidgets.QWidget(Dialog)
        self.title_bar.setMinimumSize(QtCore.QSize(0, 23))
        self.title_bar.setStyleSheet("QWidget #title_bar{\n"
"    background-color: rgb(0, 0, 0);\n"
"}")
        self.title_bar.setObjectName("title_bar")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.title_bar)
        self.gridLayout_8.setContentsMargins(18, 0, 8, 0)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.speed_widget = QtWidgets.QWidget(self.title_bar)
        self.speed_widget.setObjectName("speed_widget")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.speed_widget)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setHorizontalSpacing(6)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.bajada = QtWidgets.QLabel(self.speed_widget)
        self.bajada.setStyleSheet("font: bold 10pt \"Segoe UI\";")
        self.bajada.setObjectName("bajada")
        self.gridLayout_4.addWidget(self.bajada, 0, 3, 1, 1)
        self.subida = QtWidgets.QLabel(self.speed_widget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.subida.setFont(font)
        self.subida.setStyleSheet("font: bold 10pt \"Segoe UI\";")
        self.subida.setObjectName("subida")
        self.gridLayout_4.addWidget(self.subida, 0, 2, 1, 1)
        self.gridLayout_8.addWidget(self.speed_widget, 0, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_8.addItem(spacerItem, 0, 1, 1, 1)
        self.max = QtWidgets.QToolButton(self.title_bar)
        self.max.setMinimumSize(QtCore.QSize(23, 23))
        self.max.setMaximumSize(QtCore.QSize(23, 23))
        self.max.setStyleSheet("QToolButton{\n"
"background-color: transparent;\n"
"border-radius:5px;\n"
"padding:2px;\n"
"}\n"
"QToolButton:hover{\n"
"    \n"
"    background-color: rgb(0, 200, 255);\n"
"}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("graphics/maximize.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.max.setIcon(icon1)
        self.max.setAutoRaise(True)
        self.max.setObjectName("max")
        self.gridLayout_8.addWidget(self.max, 0, 2, 1, 1)
        self.cerrar = QtWidgets.QToolButton(self.title_bar)
        self.cerrar.setMinimumSize(QtCore.QSize(23, 23))
        self.cerrar.setMaximumSize(QtCore.QSize(23, 23))
        self.cerrar.setStyleSheet("QToolButton{\n"
"background-color: transparent;\n"
"border-radius:5px;\n"
"padding:2px;\n"
"}\n"
"QToolButton:hover{\n"
"    \n"
"    background-color: red;\n"
"}")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("graphics/btn_close_h@2x.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.cerrar.setIcon(icon2)
        self.cerrar.setAutoRaise(True)
        self.cerrar.setObjectName("cerrar")
        self.gridLayout_8.addWidget(self.cerrar, 0, 3, 1, 1)
        self.gridLayout_2.addWidget(self.title_bar, 0, 0, 1, 2)
        self.widget = QtWidgets.QWidget(Dialog)
        self.widget.setObjectName("widget")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_9.setContentsMargins(-1, 0, -1, 0)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.scrollArea = QtWidgets.QScrollArea(self.widget)
        self.scrollArea.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.scrollArea.setStyleSheet("background-color:transparent;")
        self.scrollArea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrollArea.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 185, 246))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout.setContentsMargins(-1, 0, -1, -1)
        self.gridLayout.setObjectName("gridLayout")
        self.bono_lte_wget = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.bono_lte_wget.setObjectName("bono_lte_wget")
        self.bono_lte_grid = QtWidgets.QGridLayout(self.bono_lte_wget)
        self.bono_lte_grid.setContentsMargins(0, 0, 0, 0)
        self.bono_lte_grid.setObjectName("bono_lte_grid")
        self.label_7 = QtWidgets.QLabel(self.bono_lte_wget)
        self.label_7.setMinimumSize(QtCore.QSize(20, 20))
        self.label_7.setMaximumSize(QtCore.QSize(20, 20))
        self.label_7.setText("")
        self.label_7.setPixmap(QtGui.QPixmap("icons/google_calendar_4.png"))
        self.label_7.setScaledContents(True)
        self.label_7.setObjectName("label_7")
        self.bono_lte_grid.addWidget(self.label_7, 0, 0, 1, 1)
        self.bono_lte = QtWidgets.QLabel(self.bono_lte_wget)
        self.bono_lte.setTextFormat(QtCore.Qt.TextFormat.PlainText)
        self.bono_lte.setObjectName("bono_lte")
        self.bono_lte_grid.addWidget(self.bono_lte, 0, 1, 1, 1)
        self.gridLayout.addWidget(self.bono_lte_wget, 2, 0, 1, 1)
        self.bolsa_diaria_wget = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.bolsa_diaria_wget.setObjectName("bolsa_diaria_wget")
        self.bolsa_diaria_grid = QtWidgets.QGridLayout(self.bolsa_diaria_wget)
        self.bolsa_diaria_grid.setContentsMargins(0, 0, 0, 0)
        self.bolsa_diaria_grid.setObjectName("bolsa_diaria_grid")
        self.label_3 = QtWidgets.QLabel(self.bolsa_diaria_wget)
        self.label_3.setMinimumSize(QtCore.QSize(20, 20))
        self.label_3.setMaximumSize(QtCore.QSize(20, 20))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("icons/weather_swan.png"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.bolsa_diaria_grid.addWidget(self.label_3, 0, 0, 1, 1)
        self.diaria = QtWidgets.QLabel(self.bolsa_diaria_wget)
        self.diaria.setTextFormat(QtCore.Qt.TextFormat.PlainText)
        self.diaria.setObjectName("diaria")
        self.bolsa_diaria_grid.addWidget(self.diaria, 0, 1, 1, 1)
        self.gridLayout.addWidget(self.bolsa_diaria_wget, 4, 0, 1, 1)
        self.bono_datos_wget = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.bono_datos_wget.setObjectName("bono_datos_wget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.bono_datos_wget)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.bono_datos = QtWidgets.QLabel(self.bono_datos_wget)
        self.bono_datos.setObjectName("bono_datos")
        self.gridLayout_3.addWidget(self.bono_datos, 0, 1, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.bono_datos_wget)
        self.label_11.setMinimumSize(QtCore.QSize(20, 20))
        self.label_11.setMaximumSize(QtCore.QSize(20, 20))
        self.label_11.setText("")
        self.label_11.setPixmap(QtGui.QPixmap("icons/feedly (2).png"))
        self.label_11.setScaledContents(True)
        self.label_11.setObjectName("label_11")
        self.gridLayout_3.addWidget(self.label_11, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.bono_datos_wget, 3, 0, 1, 1)
        self.internacionales_wget = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.internacionales_wget.setObjectName("internacionales_wget")
        self.internacional_wget = QtWidgets.QGridLayout(self.internacionales_wget)
        self.internacional_wget.setContentsMargins(0, 0, 0, 0)
        self.internacional_wget.setObjectName("internacional_wget")
        self.internacional = QtWidgets.QLabel(self.internacionales_wget)
        self.internacional.setMinimumSize(QtCore.QSize(0, 0))
        self.internacional.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.internacional.setFont(font)
        self.internacional.setTextFormat(QtCore.Qt.TextFormat.PlainText)
        self.internacional.setObjectName("internacional")
        self.internacional_wget.addWidget(self.internacional, 0, 2, 1, 1)
        self.label = QtWidgets.QLabel(self.internacionales_wget)
        self.label.setMinimumSize(QtCore.QSize(20, 20))
        self.label.setMaximumSize(QtCore.QSize(20, 20))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("icons/navyfederal.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.internacional_wget.addWidget(self.label, 0, 1, 1, 1)
        self.gridLayout.addWidget(self.internacionales_wget, 0, 0, 1, 1)
        self.correo_wget = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.correo_wget.setObjectName("correo_wget")
        self.correo_grid = QtWidgets.QGridLayout(self.correo_wget)
        self.correo_grid.setContentsMargins(0, 0, 0, 0)
        self.correo_grid.setObjectName("correo_grid")
        self.label_5 = QtWidgets.QLabel(self.correo_wget)
        self.label_5.setMinimumSize(QtCore.QSize(20, 20))
        self.label_5.setMaximumSize(QtCore.QSize(20, 20))
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap("icons/email.png"))
        self.label_5.setScaledContents(True)
        self.label_5.setObjectName("label_5")
        self.correo_grid.addWidget(self.label_5, 0, 0, 1, 1)
        self.correo = QtWidgets.QLabel(self.correo_wget)
        self.correo.setTextFormat(QtCore.Qt.TextFormat.PlainText)
        self.correo.setObjectName("correo")
        self.correo_grid.addWidget(self.correo, 0, 1, 1, 1)
        self.gridLayout.addWidget(self.correo_wget, 6, 0, 1, 1)
        self.nacionales_wget = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.nacionales_wget.setObjectName("nacionales_wget")
        self.nacionales_grid = QtWidgets.QGridLayout(self.nacionales_wget)
        self.nacionales_grid.setContentsMargins(0, 0, 0, 0)
        self.nacionales_grid.setObjectName("nacionales_grid")
        self.label_4 = QtWidgets.QLabel(self.nacionales_wget)
        self.label_4.setMinimumSize(QtCore.QSize(20, 20))
        self.label_4.setMaximumSize(QtCore.QSize(20, 20))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("icons/1f1e8-1f1fa.png"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.nacionales_grid.addWidget(self.label_4, 0, 0, 1, 1)
        self.nacionales = QtWidgets.QLabel(self.nacionales_wget)
        self.nacionales.setTextFormat(QtCore.Qt.TextFormat.PlainText)
        self.nacionales.setObjectName("nacionales")
        self.nacionales_grid.addWidget(self.nacionales, 0, 1, 1, 1)
        self.gridLayout.addWidget(self.nacionales_wget, 5, 0, 1, 1)
        self.lte_wget = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.lte_wget.setObjectName("lte_wget")
        self.lte_grid = QtWidgets.QGridLayout(self.lte_wget)
        self.lte_grid.setContentsMargins(0, 0, 0, 0)
        self.lte_grid.setObjectName("lte_grid")
        self.label_2 = QtWidgets.QLabel(self.lte_wget)
        self.label_2.setMinimumSize(QtCore.QSize(20, 20))
        self.label_2.setMaximumSize(QtCore.QSize(20, 20))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("icons/flashify.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.lte_grid.addWidget(self.label_2, 0, 0, 1, 1)
        self.lte = QtWidgets.QLabel(self.lte_wget)
        self.lte.setTextFormat(QtCore.Qt.TextFormat.PlainText)
        self.lte.setObjectName("lte")
        self.lte_grid.addWidget(self.lte, 0, 1, 1, 1)
        self.gridLayout.addWidget(self.lte_wget, 1, 0, 1, 1)
        self.saldo_wget = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.saldo_wget.setObjectName("saldo_wget")
        self.saldo_grid = QtWidgets.QGridLayout(self.saldo_wget)
        self.saldo_grid.setContentsMargins(0, 0, 0, 0)
        self.saldo_grid.setObjectName("saldo_grid")
        self.label_6 = QtWidgets.QLabel(self.saldo_wget)
        self.label_6.setMinimumSize(QtCore.QSize(20, 20))
        self.label_6.setMaximumSize(QtCore.QSize(20, 20))
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap("icons/moneywise.png"))
        self.label_6.setScaledContents(True)
        self.label_6.setObjectName("label_6")
        self.saldo_grid.addWidget(self.label_6, 0, 0, 1, 1)
        self.saldo = QtWidgets.QLabel(self.saldo_wget)
        self.saldo.setTextFormat(QtCore.Qt.TextFormat.PlainText)
        self.saldo.setObjectName("saldo")
        self.saldo_grid.addWidget(self.saldo, 0, 1, 1, 1)
        self.gridLayout.addWidget(self.saldo_wget, 7, 0, 1, 1)
        self.bono_saldo_wget = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.bono_saldo_wget.setObjectName("bono_saldo_wget")
        self.bono_saldo_grid = QtWidgets.QGridLayout(self.bono_saldo_wget)
        self.bono_saldo_grid.setContentsMargins(0, 0, 0, 0)
        self.bono_saldo_grid.setObjectName("bono_saldo_grid")
        self.label_8 = QtWidgets.QLabel(self.bono_saldo_wget)
        self.label_8.setMinimumSize(QtCore.QSize(20, 20))
        self.label_8.setMaximumSize(QtCore.QSize(20, 20))
        self.label_8.setText("")
        self.label_8.setPixmap(QtGui.QPixmap("icons/moneymanager.png"))
        self.label_8.setScaledContents(True)
        self.label_8.setObjectName("label_8")
        self.bono_saldo_grid.addWidget(self.label_8, 0, 0, 1, 1)
        self.bono = QtWidgets.QLabel(self.bono_saldo_wget)
        self.bono.setTextFormat(QtCore.Qt.TextFormat.PlainText)
        self.bono.setObjectName("bono")
        self.bono_saldo_grid.addWidget(self.bono, 0, 1, 1, 1)
        self.gridLayout.addWidget(self.bono_saldo_wget, 8, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_9.addWidget(self.scrollArea, 0, 0, 1, 1)
        self.ntw_status = QtWidgets.QLabel(self.widget)
        self.ntw_status.setMinimumSize(QtCore.QSize(25, 25))
        self.ntw_status.setMaximumSize(QtCore.QSize(25, 25))
        self.ntw_status.setText("")
        self.ntw_status.setPixmap(QtGui.QPixmap("icons/unavailabe_network.png"))
        self.ntw_status.setScaledContents(True)
        self.ntw_status.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.ntw_status.setObjectName("ntw_status")
        self.gridLayout_9.addWidget(self.ntw_status, 0, 3, 1, 1)
        self.widget_2 = QtWidgets.QWidget(self.widget)
        self.widget_2.setObjectName("widget_2")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.widget_2)
        self.gridLayout_7.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_7.setSpacing(0)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.more_info_widget = QtWidgets.QWidget(self.widget_2)
        self.more_info_widget.setObjectName("more_info_widget")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.more_info_widget)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_6.setSpacing(0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.gridLayout_7.addWidget(self.more_info_widget, 0, 0, 1, 1)
        self.control_widget = QtWidgets.QWidget(self.widget_2)
        self.control_widget.setObjectName("control_widget")
        self.control = QtWidgets.QGridLayout(self.control_widget)
        self.control.setContentsMargins(0, 0, 0, 0)
        self.control.setSpacing(0)
        self.control.setObjectName("control")
        self.gridLayout_7.addWidget(self.control_widget, 0, 1, 1, 1)
        self.gridLayout_9.addWidget(self.widget_2, 0, 4, 1, 1)
        self.time_widget = QtWidgets.QWidget(self.widget)
        self.time_widget.setObjectName("time_widget")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.time_widget)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_10 = QtWidgets.QLabel(self.time_widget)
        self.label_10.setMinimumSize(QtCore.QSize(20, 20))
        self.label_10.setMaximumSize(QtCore.QSize(20, 20))
        self.label_10.setText("")
        self.label_10.setPixmap(QtGui.QPixmap("icons/time.png"))
        self.label_10.setScaledContents(True)
        self.label_10.setObjectName("label_10")
        self.gridLayout_5.addWidget(self.label_10, 0, 0, 1, 1)
        self.hora_act = QtWidgets.QLabel(self.time_widget)
        self.hora_act.setObjectName("hora_act")
        self.gridLayout_5.addWidget(self.hora_act, 0, 1, 1, 1)
        self.gridLayout_9.addWidget(self.time_widget, 0, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_9.addItem(spacerItem1, 0, 2, 1, 1)
        self.gridLayout_2.addWidget(self.widget, 1, 0, 1, 2)
        self.actionSalir = QtWidgets.QAction(Dialog)
        self.actionSalir.setObjectName("actionSalir")

        self.retranslateUi(Dialog)
        self.cerrar.clicked.connect(Dialog.close) # type: ignore
        self.max.clicked.connect(Dialog.hide) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "TuCubacel Watchtower - Ventana flotante"))
        self.bajada.setText(_translate("Dialog", "↓ 0.0 kB/s"))
        self.subida.setText(_translate("Dialog", "↑ 0.0 kB/s"))
        self.max.setToolTip(_translate("Dialog", "Cambiar a ventana principal"))
        self.max.setText(_translate("Dialog", "..."))
        self.cerrar.setToolTip(_translate("Dialog", "Cerrar ventana flotante"))
        self.cerrar.setText(_translate("Dialog", "..."))
        self.bono_lte.setText(_translate("Dialog", "0.0 Mb"))
        self.diaria.setText(_translate("Dialog", "0.0 Mb"))
        self.bono_datos.setText(_translate("Dialog", "0.0 MB"))
        self.internacional.setText(_translate("Dialog", "0.0 Mb"))
        self.correo.setText(_translate("Dialog", "0.0 Mb"))
        self.nacionales.setText(_translate("Dialog", "0.0 Mb"))
        self.lte.setText(_translate("Dialog", "0.0 Mb"))
        self.saldo.setText(_translate("Dialog", "$ 0.0"))
        self.bono.setText(_translate("Dialog", "$ 0.0"))
        self.ntw_status.setToolTip(_translate("Dialog", "Sin conexión"))
        self.hora_act.setText(_translate("Dialog", "--:--:--"))
        self.actionSalir.setText(_translate("Dialog", "salir"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
