# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'packages_register.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(743, 564)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        Dialog.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/actionlauncher.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        Dialog.setStyleSheet("QComboBox\n"
"{\n"
"    color: rgb(0, 0, 0);\n"
"    font: 12pt \"Calibri\";\n"
"    /*selection-background-color: #3daee9;*/\n"
"    border-radius:12px;\n"
"    border:none;\n"
"    padding-left: 10px;\n"
"    padding-right: 10px;\n"
"    selection-background-color: rgb(62, 62, 62);\n"
"    min-width: 75px;\n"
"}\n"
"\n"
"QComboBox:drop-down {\n"
"    color: white;\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    width: 12px;\n"
"    border:none;\n"
"    border-radius:10px;\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"QComboBox:down-arrow {\n"
"    image: url(\'ui/graphics/arrow_down.png\');\n"
"    height: 12px;\n"
"    width: 12px;\n"
"    padding-right: 10px;\n"
"}\n"
"\n"
"QComboBox:on:hover:focus {\n"
"    image: url(\'ui/graphics/arrow_down_disabled.png\');\n"
"}\n"
"\n"
"QComboBox QAbstractItemView\n"
"{\n"
"    color: white;\n"
"    background-color: #232629;\n"
"    border-radius: 10px;\n"
"    border: none;\n"
"    selection-background-color: #18465d;\n"
"}\n"
"/* DATE PICKER */\n"
"QDateEdit\n"
"{\n"
"    color: rgb(0, 0, 0);\n"
"    border-radius:12px;\n"
"    border:none;\n"
"    padding-left: 10px;\n"
"    padding-right: 10px;\n"
"    selection-background-color: #3daee9;\n"
"}\n"
"\n"
"QDateEdit::down-arrow\n"
"{\n"
"    image: url(\'ui/graphics/arrow_down.png\');\n"
"    height: 12px;\n"
"    width: 12px;\n"
"    padding-right: 10px;\n"
"}\n"
"\n"
"QDateEdit:on\n"
"{\n"
"    padding-top: 3px;\n"
"    padding-left: 4px;\n"
"    selection-background-color: #4a4a4a;\n"
"}\n"
"\n"
"QDateEdit QAbstractItemView\n"
"{\n"
"    \n"
"    color:rgb(181, 181, 181);\n"
"    background-color: #232629;\n"
"    border-radius: 5px;\n"
"    border: 1px solid #3375A3;\n"
"    selection-background-color: #3daee9;\n"
"}\n"
"\n"
"QDateEdit::drop-down\n"
"{\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    width: 15px;\n"
"    /*border-left-width: 0px;\n"
"    border-left-color: darkgray;\n"
"    border-left-style: solid;*/\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QDateEdit::down-arrow:on, QDateEdit::down-arrow:hover,\n"
"QDateEdit::down-arrow:focus\n"
"{\n"
"    image: url(\'ui/graphics/arrow_down.png\');\n"
"    height: 12px;\n"
"    width: 12px;\n"
"    padding-right: 10px;\n"
"}")
        Dialog.setModal(False)
        self.gridLayout_4 = QtWidgets.QGridLayout(Dialog)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setVerticalSpacing(0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.table = QtWidgets.QTableWidget(Dialog)
        self.table.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.table.setAlternatingRowColors(True)
        self.table.setTextElideMode(QtCore.Qt.ElideMiddle)
        self.table.setObjectName("table")
        self.table.setColumnCount(5)
        self.table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(4, item)
        self.table.horizontalHeader().setStretchLastSection(True)
        self.table.verticalHeader().setStretchLastSection(False)
        self.gridLayout_4.addWidget(self.table, 3, 0, 1, 1)
        self.widget = QtWidgets.QWidget(Dialog)
        self.widget.setMinimumSize(QtCore.QSize(0, 0))
        self.widget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.widget.setStyleSheet("QWidget{\n"
"font: 12pt \"Calibri\";\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QWidget #widget{\n"
"    background-color: rgb(68, 68, 68);\n"
"}")
        self.widget.setObjectName("widget")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")
        self.gridLayout_5.addWidget(self.label, 1, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setObjectName("label_2")
        self.gridLayout_5.addWidget(self.label_2, 1, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setObjectName("label_3")
        self.gridLayout_5.addWidget(self.label_3, 1, 2, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setObjectName("label_4")
        self.gridLayout_5.addWidget(self.label_4, 1, 3, 1, 1)
        self.init_day = QtWidgets.QDateEdit(self.widget)
        self.init_day.setMinimumSize(QtCore.QSize(0, 25))
        self.init_day.setStyleSheet("color: rgb(0, 0, 0);")
        self.init_day.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.init_day.setCalendarPopup(True)
        self.init_day.setObjectName("init_day")
        self.gridLayout_5.addWidget(self.init_day, 2, 0, 1, 1)
        self.final_date = QtWidgets.QDateEdit(self.widget)
        self.final_date.setMinimumSize(QtCore.QSize(0, 25))
        self.final_date.setStyleSheet("color: rgb(0, 0, 0);")
        self.final_date.setFrame(False)
        self.final_date.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.final_date.setCalendarPopup(True)
        self.final_date.setObjectName("final_date")
        self.gridLayout_5.addWidget(self.final_date, 2, 1, 1, 1)
        self.origins_list = QtWidgets.QComboBox(self.widget)
        self.origins_list.setMinimumSize(QtCore.QSize(95, 25))
        self.origins_list.setStyleSheet("color: grey;")
        self.origins_list.setObjectName("origins_list")
        self.gridLayout_5.addWidget(self.origins_list, 2, 2, 1, 1)
        self.data_package_list = QtWidgets.QComboBox(self.widget)
        self.data_package_list.setMinimumSize(QtCore.QSize(95, 25))
        self.data_package_list.setStyleSheet("color: grey;")
        self.data_package_list.setObjectName("data_package_list")
        self.gridLayout_5.addWidget(self.data_package_list, 2, 3, 1, 1)
        self.send = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.send.setFont(font)
        self.send.setStyleSheet("QPushButton{\n"
"    \n"
"    font: bold 12pt \"Calibri\";\n"
"    color:rgba(0, 0, 0, 100);\n"
"    border-radius: 10px;\n"
"    padding: 5px;\n"
"    background-color: rgb(190, 174, 255);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    color:rgba(255, 255, 255, 100);\n"
"    background-color:rgb(82, 62, 106);\n"
"}")
        self.send.setObjectName("send")
        self.gridLayout_5.addWidget(self.send, 2, 4, 1, 1)
        self.widget_4 = QtWidgets.QWidget(self.widget)
        self.widget_4.setObjectName("widget_4")
        self.gridLayout = QtWidgets.QGridLayout(self.widget_4)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.btn_minimize = QtWidgets.QPushButton(self.widget_4)
        self.btn_minimize.setMinimumSize(QtCore.QSize(16, 16))
        self.btn_minimize.setMaximumSize(QtCore.QSize(17, 17))
        self.btn_minimize.setStyleSheet("QPushButton {\n"
"    border: none;\n"
"    border-radius: 8px;        \n"
"    background-color: rgb(255, 170, 0);\n"
"}\n"
"QPushButton:hover {    \n"
"    background-color: rgba(255, 170, 0, 150);\n"
"}")
        self.btn_minimize.setText("")
        self.btn_minimize.setObjectName("btn_minimize")
        self.gridLayout.addWidget(self.btn_minimize, 0, 2, 1, 1)
        self.btn_close = QtWidgets.QPushButton(self.widget_4)
        self.btn_close.setMinimumSize(QtCore.QSize(16, 16))
        self.btn_close.setMaximumSize(QtCore.QSize(17, 17))
        self.btn_close.setStyleSheet("QPushButton {\n"
"    border: none;\n"
"    border-radius: 8px;        \n"
"    background-color: rgb(255, 0, 0);\n"
"}\n"
"QPushButton:hover {        \n"
"    background-color: rgba(255, 0, 0, 150);\n"
"}")
        self.btn_close.setText("")
        self.btn_close.setObjectName("btn_close")
        self.gridLayout.addWidget(self.btn_close, 0, 3, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.widget_4)
        self.label_8.setText("")
        self.label_8.setPixmap(QtGui.QPixmap("images/cubacel.png"))
        self.label_8.setScaledContents(True)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 0, 0, 1, 1)
        self.gridLayout_5.addWidget(self.widget_4, 0, 0, 1, 5)
        self.gridLayout_4.addWidget(self.widget, 0, 0, 1, 1, QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.widget_3 = QtWidgets.QWidget(Dialog)
        self.widget_3.setStyleSheet("QWidget #widget_3{\n"
"    \n"
"    background-color: rgb(203, 203, 203);\n"
"}")
        self.widget_3.setObjectName("widget_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.widget_3)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_7 = QtWidgets.QLabel(self.widget_3)
        self.label_7.setMinimumSize(QtCore.QSize(30, 30))
        self.label_7.setMaximumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setText("")
        self.label_7.setPixmap(QtGui.QPixmap("icons/search_black.png"))
        self.label_7.setScaledContents(True)
        self.label_7.setObjectName("label_7")
        self.gridLayout_3.addWidget(self.label_7, 1, 0, 1, 1)
        self.search_by = QtWidgets.QLineEdit(self.widget_3)
        self.search_by.setMinimumSize(QtCore.QSize(0, 25))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.search_by.setFont(font)
        self.search_by.setStyleSheet("border-radius:12px;\n"
"border:none;\n"
"padding-left: 10px;\n"
"padding-right: 10px;")
        self.search_by.setClearButtonEnabled(True)
        self.search_by.setObjectName("search_by")
        self.gridLayout_3.addWidget(self.search_by, 1, 1, 1, 1)
        self.widget_2 = QtWidgets.QWidget(self.widget_3)
        self.widget_2.setObjectName("widget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_5 = QtWidgets.QLabel(self.widget_2)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 0, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.widget_2)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 0, 2, 1, 1)
        self.results = QtWidgets.QComboBox(self.widget_2)
        self.results.setMinimumSize(QtCore.QSize(95, 25))
        self.results.setMaximumSize(QtCore.QSize(20, 16777215))
        self.results.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(156, 156, 156);\n"
"/*padding-right: 20px;\n"
"padding-left: 20px;*/")
        self.results.setObjectName("results")
        self.results.addItem("")
        self.results.addItem("")
        self.results.addItem("")
        self.results.addItem("")
        self.gridLayout_2.addWidget(self.results, 0, 1, 1, 1)
        self.gridLayout_3.addWidget(self.widget_2, 0, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.gridLayout_4.addWidget(self.widget_3, 2, 0, 1, 1)

        self.retranslateUi(Dialog)
        self.btn_close.clicked['bool'].connect(Dialog.close)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Registro de compras"))
        self.table.setSortingEnabled(True)
        item = self.table.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "Fecha"))
        item = self.table.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Número de teléfono"))
        item = self.table.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "Origen"))
        item = self.table.horizontalHeaderItem(3)
        item.setText(_translate("Dialog", "Paquete"))
        item = self.table.horizontalHeaderItem(4)
        item.setText(_translate("Dialog", "Precio"))
        self.label.setText(_translate("Dialog", "Fecha Inicio:"))
        self.label_2.setText(_translate("Dialog", "Fecha Final:"))
        self.label_3.setText(_translate("Dialog", "Origen"))
        self.label_4.setText(_translate("Dialog", "Paquete"))
        self.send.setToolTip(_translate("Dialog", "Enviar solicitud"))
        self.send.setText(_translate("Dialog", "Enviar"))
        self.btn_minimize.setToolTip(_translate("Dialog", "Minimizar"))
        self.btn_close.setToolTip(_translate("Dialog", "Cerrar"))
        self.search_by.setPlaceholderText(_translate("Dialog", "Escriba un criterio de busqueda"))
        self.label_5.setText(_translate("Dialog", "Mostrar"))
        self.label_6.setText(_translate("Dialog", "resultados"))
        self.results.setItemText(0, _translate("Dialog", "10"))
        self.results.setItemText(1, _translate("Dialog", "25"))
        self.results.setItemText(2, _translate("Dialog", "50"))
        self.results.setItemText(3, _translate("Dialog", "100"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
