# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/pamarillas_listitem.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(781, 132)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setMaximumSize(QtCore.QSize(16777215, 132))
        Form.setStyleSheet("QWidget#Form{\n"
"    background-color: rgb(93, 93, 93);\n"
"}\n"
"\n"
"QLabel{\n"
"    color: rgb(255, 255, 255);\n"
"    font: 10pt \"Segoe UI\";\n"
"}\n"
"QPlainTextEdit{\n"
"    border:none;\n"
"    color: rgb(255, 255, 255);\n"
"    font: bold 12pt \"Segoe UI\";\n"
"    background:transparent;\n"
"}")
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout.setObjectName("gridLayout")
        self.img_lbl = QtWidgets.QLabel(Form)
        self.img_lbl.setMinimumSize(QtCore.QSize(100, 100))
        self.img_lbl.setMaximumSize(QtCore.QSize(100, 100))
        self.img_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.img_lbl.setObjectName("img_lbl")
        self.gridLayout.addWidget(self.img_lbl, 2, 0, 1, 1)
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setObjectName("widget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.title_lbl = QtWidgets.QLabel(self.widget)
        self.title_lbl.setStyleSheet("font: bold 12pt \"Segoe UI\";")
        self.title_lbl.setObjectName("title_lbl")
        self.gridLayout_2.addWidget(self.title_lbl, 0, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 1, 1, 1)
        self.category_lbl = QtWidgets.QLabel(self.widget)
        self.category_lbl.setStyleSheet("font: bold 10pt \"Segoe UI\";")
        self.category_lbl.setObjectName("category_lbl")
        self.gridLayout_2.addWidget(self.category_lbl, 1, 0, 1, 1)
        self.phone_list = QtWidgets.QPlainTextEdit(self.widget)
        self.phone_list.setMaximumSize(QtCore.QSize(150, 16777215))
        self.phone_list.setReadOnly(True)
        self.phone_list.setObjectName("phone_list")
        self.gridLayout_2.addWidget(self.phone_list, 1, 1, 2, 1)
        self.address_lbl = QtWidgets.QLabel(self.widget)
        self.address_lbl.setObjectName("address_lbl")
        self.gridLayout_2.addWidget(self.address_lbl, 2, 0, 1, 1)
        self.gridLayout.addWidget(self.widget, 2, 1, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.img_lbl.setText(_translate("Form", "Imagen"))
        self.title_lbl.setText(_translate("Form", "Título"))
        self.label.setText(_translate("Form", "Teléfonos"))
        self.category_lbl.setText(_translate("Form", "Categoría"))
        self.phone_list.setPlaceholderText(_translate("Form", "(sin teléfonos)"))
        self.address_lbl.setText(_translate("Form", "Dirección"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
