# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'service_purchase_backup.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import pyqtSignal
from PyQt5.QtWidgets import QWidget


class ProductInfo(QWidget):
    send = pyqtSignal(str)
    def __init__(self, categ, title, details, price, link, parent=None):
        QWidget.__init__(self)
        #
        self.parent= parent
        self.link = link
        #
        self.setObjectName("Widget")
        self.setMinimumSize(320, 176)
        self.setMinimumSize(320, 176-+40)
        #self.main_widget = QWidget(self)
        #self.main_layout = QVBoxLayout(self.main_widget)
        #self.setStyleSheet("QWidget{\n"
#"    background-color: rgb(68, 68, 68);\n"
#"}")
        self.gridLayout = QtWidgets.QGridLayout(self)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.body_widget = QtWidgets.QWidget(self)
        self.body_widget.setMinimumSize(QtCore.QSize(0, 100))
        self.body_widget.setStyleSheet("QWidget{\n"
"    font-family:\"Calibri\";\n"
"    border-radius: 15px;\n"
"    padding: 5px;\n"
"    background-color: rgb(77, 77, 127);\n"
"}")
        self.body_widget.setObjectName("body_widget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.body_widget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.details = QtWidgets.QLabel(self.body_widget)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.details.setFont(font)
        self.details.setStyleSheet("color: rgba(255, 255, 255, 100);")
        self.details.setObjectName("details")
        self.details.setText(details)
        self.gridLayout_2.addWidget(self.details, 1, 0, 1, 1)
        self.price = QtWidgets.QLabel(self.body_widget)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.price.setFont(font)
        self.price.setStyleSheet("color: rgb(255, 255, 255);")
        self.price.setObjectName("price")
        self.price.setText(price)
        self.gridLayout_2.addWidget(self.price, 2, 0, 1, 1)
        self.purchase = QtWidgets.QPushButton(self.body_widget)
        self.purchase.setText("COMPRAR")
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.purchase.setFont(font)
        self.purchase.setStyleSheet("QPushButton{\n"
"    color:rgba(0, 0, 0, 100);\n"
"    border-radius: 10px;\n"
"    padding: 5px;\n"
"    background-color: rgb(190, 174, 255);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    color:rgba(255, 255, 255, 100);\n"
"    background-color:rgb(82, 62, 106);\n"
"}")
        self.purchase.setObjectName("purchase")
        self.gridLayout_2.addWidget(self.purchase, 3, 0, 1, 1)
        self.head = QtWidgets.QWidget(self.body_widget)
        self.head.setObjectName("head")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.head)
        self.gridLayout_4.setContentsMargins(0, -1, 0, -1)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.name = QtWidgets.QLabel(self.head)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.name.setFont(font)
        self.name.setStyleSheet("color: rgb(255, 255, 255);")
        self.name.setWordWrap(True)
        self.name.setObjectName("name")
        self.name.setText(title)
        self.gridLayout_4.addWidget(self.name, 0, 0, 1, 1)
        self.category = QtWidgets.QLabel(self.head)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.category.setFont(font)
        self.category.setStyleSheet("color: rgba(255, 255, 255, 100);")
        self.category.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.category.setWordWrap(True)
        self.category.setObjectName("category")
        self.category.setText(categ)
        self.gridLayout_4.addWidget(self.category, 0, 1, 1, 1)
        self.gridLayout_2.addWidget(self.head, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.body_widget, 0, 0, 1, 1)

        self.purchase.clicked.connect(lambda: self.send.emit(self.link))
        QtCore.QMetaObject.connectSlotsByName(self)


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ui = ProductInfo()
    ui.show()
    sys.exit(app.exec_())
